core/calls/urls.py
from django.contrib import admin
from django.urls import path, include  # add this
from . import views

app_name = 'calls'
urlpatterns = [

    path('customers_list',views.customers_list,name='call_list'),
    path('follow_up_calls_today',views.Follow_up_calls_today,name='Follow_up_calls'),
    path('follow_up_calls_all',views.Follow_up_calls_all,name='Follow_up_calls_all'),
    path('call/<int:id>/', views.make_call, name='make_call'),


]

core/core/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.contrib import admin
from django.urls import path, include  # add this

urlpatterns = [
    path('admin/', admin.site.urls),          # Django admin route
    #path('admin' , admin.site.urls),          # Django admin route 
    path("", include("authentication.urls")), # Auth routes - login / register
    path("", include("app.urls"))  ,           # UI Kits Html files
    path("", include("testapp.urls")),
    path("", include("novav1.urls")),
    path("", include("event_manage.urls")),
    path("", include("calls.urls")),
    path("select2/", include("django_select2.urls")),
]

core/urls.py
from django.contrib import admin
from django.urls import  path

from . import views

urlpatterns = [
    path("newPatient", views.PatientCreateView.as_view(), name="Patient-create"),
    path("newreservation", views.ReservationCreateView.as_view(), name="Reservation-create"),
    path("datareservation", views.ReservationData.as_view(), name="Reservation-data"),
    path("PackagesCreate", views.PackagesCreateView.as_view(), name="Packages-create"),
    path('Patientsearch/',views.Search,name="Patient-search"),
    path("roomCreate", views.RoomCreateView.as_view(), name="room-create"),
    path("area", views.AreaCreateView.as_view(), name="area-create"),
    path("Branch", views.BranchCreateView.as_view(), name="branch-create"), 
    path("Device", views.DeviceCreateView.as_view(), name="Device-create"), 
    path("DoctorIn", views.DoctorInCreateView.as_view(), name="DoctorIn-create"), 
    path("DoctorOut", views.DoctorOutCreateView.as_view(), name="DoctorOut-create"), 
 
    path("adddoctor", views.AddDodtonIN.as_view(), name="add-doctor"),
    path('PackagesCreate/<int:id>/', views.onofPatient, name='onof-Patient'),
    path('area/<int:id>/', views.onofArea, name='onof-Area'),
    path('Branch/<int:id>/', views.onofBranch, name='onof-Branch'),
    path('Device/<int:id>/', views.onofDevice, name='onof-Device'),
    path('DoctorIn/<int:id>/', views.onofDoctorIn, name='onof-DoctorIn'),
    path('DoctorOut/<int:id>/', views.onofDoctorOut, name='onof-DoctorOut'),   
    #path('toggle/', views.toggle),
    path('<int:id>/', views.onofPackages, name='onofPackages'),
    path('Patientdetail/<int:id>/', views.PatientDetailView, name='Patient-detail'),
    path('', views.index, name='index'),
]

core/calls/models.py
from django.db import models

# Create your models here.
from datetime import datetime ,timedelta
from django.utils.timezone import now
from novav1.models import Patient
from django.contrib.auth.models import User
import time
import math
import datetime
from django.conf import settings
LABEL_CHOICES = (
    
    (1, '1 day'),
    (2, '2days'),
    (3, '3days'),
    (4, '4days'),
    (5, '5days'),
    (6, '6days'),
    (7, 'week'),
    (14, 'weeks'),
    (30, 'Month')
)

class statue(models.Model):
    statue=models.CharField(max_length=10)


    def __str__(self):
        return str(self.statue)


class calls(models.Model):
    Customer     = models.ForeignKey("novav1.Patient", on_delete=models.CASCADE ,blank=True,null=True)
    user         = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,blank=True,null=True)
    Note         = models.TextField(max_length=100)
    Statue       = models.ForeignKey("statue", on_delete=models.CASCADE)
    Calldate     = models.DateField(default=datetime.datetime.now,blank=True,null=True)
    Followup     = models.IntegerField(choices=LABEL_CHOICES,blank=True,null=True)
    FollowupIN = models.DateField(blank=True,null=True)

    def __str__(self):
        return str(self.Customer)


    def FollowupDate(self):
        sd = self.Calldate
        days = self.Followup
        ed = datetime.timedelta(days=-days)
        print(ed)
        Followupdate = sd-ed
                
        return Followupdate       
                
            
            

    def save(self, *args, **kwargs):
        if self.Followup > 0 :
            self.FollowupIN = self.FollowupDate()
        
        super(calls, self).save(*args, **kwargs)    

core/calls/forms.py
from django import forms

from django_select2 import forms as s2forms

from . import models
from novav1.models import Packages

from django.forms.widgets import *
from crispy_forms.layout import *
from crispy_forms.helper import *
from django.template import Template, Context
from django.forms.widgets import DateInput, TextInput ,DateTimeBaseInput ,TimeInput

from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget


class callsForms(forms.ModelForm):  
    class Meta:
        model = models.calls
        fields = ['Note','Statue','Followup']    

        labels = {
            'Note': (''),
            'Statue': (''),
            'Followup': (''),
            
            
            
            }

core/calls/views.py
from django.shortcuts import render ,redirect

# Create your views here.
from .models import calls ,statue
from novav1.models import Patient
from .forms import callsForms
from django.utils.timezone import now
import time
import math
import datetime


def  customers_list(request):
    customers_list= Patient.objects.all()
    context={

        'customers_list':customers_list
    }


    return render(request,'calls/templates/call_list.html',context)



def make_call(request,id):
    calls_history= calls.objects.filter(Customer=id)
    if request.POST:
        form = callsForms(request.POST)
        if form.is_valid():
              newform = form.save(commit=False)
              newform.Customer_id = id
              newform.user= request.user
              if newform.save():
                return redirect('/customers_list')
              else:
               return redirect('/customers_list')
        else:
        
            return redirect('/')

        return redirect('/')
    else:
        form = callsForms()
        return render(request, 'calls/templates/new_call.html', {'form':form,'calls_history':calls_history})





def  Follow_up_calls_today(request):
    now = datetime.date.today()
    customers_list= calls.objects.filter(FollowupIN=now)
    context={

        'customers_list':customers_list
    }


    return render(request,'calls/templates/Follow_up_calls.html',context)


def  Follow_up_calls_all(request):
    now = datetime.date.today()
    customers_list= calls.objects.filter(FollowupIN__gte=now)
    context={

        'customers_list':customers_list
    }


    return render(request,'calls/templates/Follow_up_calls_all.html',context)    

core/calls/templates/Follow_up_calls.html
{% extends "layouts/base.html" %}

{% block title %} Tables Data {% endblock %} 

<!-- Element injected in the BODY element -->
{% block body_class %}   sidebar-mini sidebar-collapse{% endblock body_class %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="/static/assets/plugins/fontawesome-free/css/all.min.css">
  <!-- DataTables -->
  <link rel="stylesheet" href="/static/assets/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
  <link rel="stylesheet" href="/static/assets/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="/static/assets/css/adminlte.min.css">

{% endblock stylesheets %}

{% block content %} 

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Follow Up Today</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Follow Up Today</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            
            <!-- /.card -->

            <div class="card">
              <div class="card-header">
                <h3 class="card-title">Follow Up Today</h3>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="example1" class="table table-bordered table-striped">
                  <thead>
                  <tr>
                    <th>Rendering engine</th>
                    <th>Browser</th>
                    <th>Platform(s)</th>
                    <th>Engine version</th>
                    <th>CSS grade</th>
                    <th>user</th>
                    <th>action</th>
                  </tr>
                  </thead>
                  <tbody>
                  <tr>
                    {% for person in customers_list.all %}
                    <td>{{person.Customer}}</td>
                    <td>{{person.Customer.PatientMobile1}}</td>
                    <td>{{person.PatientMobile2}}</td>
                    <td> {{person.Statue}}</td>
                    <td>{{person.Calldate}}</td>
                    <td>{{person.user}}</td>
                    <td><a class="btn btn-warning" href="{% url 'calls:make_call'  person.id %}">Call</a> </td>
                  </tr>
                  {%endfor%}
                  
                  </tfoot>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
      </div>
      <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

  <!-- jQuery -->
  <script src="/static/assets/plugins/jquery/jquery.min.js"></script>
  <!-- Bootstrap 4 -->
  <script src="/static/assets/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
  <!-- DataTables -->
  <script src="/static/assets/plugins/datatables/jquery.dataTables.min.js"></script>
  <script src="/static/assets/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
  <script src="/static/assets/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
  <script src="/static/assets/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
  <!-- AdminLTE App -->
  <script src="/static/assets/js/adminlte.min.js"></script>
  <!-- AdminLTE for demo purposes -->
  <script src="/static/assets/js/demo.js"></script>
  <!-- page script -->
  <script>
    $(function () {
      $("#example1").DataTable({
        "responsive": true,
        "autoWidth": false,
      });
      $('#example2').DataTable({
        "paging": true,
        "lengthChange": false,
        "searching": false,
        "ordering": true,
        "info": true,
        "autoWidth": false,
        "responsive": true,
      });
    });
  </script>

{% endblock javascripts %}

core/calls/templates/Follow_up_calls_all.html
{% extends "layouts/base.html" %}

{% block title %} Tables Data {% endblock %} 

<!-- Element injected in the BODY element -->
{% block body_class %}  sidebar-mini sidebar-collapse {% endblock body_class %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="/static/assets/plugins/fontawesome-free/css/all.min.css">
  <!-- DataTables -->
  <link rel="stylesheet" href="/static/assets/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
  <link rel="stylesheet" href="/static/assets/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="/static/assets/css/adminlte.min.css">

{% endblock stylesheets %}

{% block content %} 

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Follow Up Call All</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Follow Up Call All </li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            
            <!-- /.card -->

            <div class="card">
              <div class="card-header">
                <h3 class="card-title">Follow Up Call All</h3>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="example1" class="table table-bordered table-striped">
                  <thead>
                  <tr>
                    <th>Rendering engine</th>
                    <th>Browser</th>
                    <th>Platform(s)</th>
                    <th>Engine version</th>
                    <th>CSS grade</th>
                    <th>user</th>
                    <th>action</th>
                  </tr>
                  </thead>
                  <tbody>
                  <tr>
                    {% for person in customers_list.all %}
                    <td>{{person.Customer}}</td>
                    <td>{{person.Customer.PatientMobile1}}</td>
                    <td>{{person.PatientMobile2}}</td>
                    <td> {{person.Statue}}</td>
                    <td>{{person.Calldate}}</td>
                    <td>{{person.user}}</td>
                    <td><a class="btn btn-warning" href="{% url 'calls:make_call'  person.id %}">Call</a> </td>
                  </tr>
                  {%endfor%}
                  
                  </tfoot>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
      </div>
      <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

  <!-- jQuery -->
  <script src="/static/assets/plugins/jquery/jquery.min.js"></script>
  <!-- Bootstrap 4 -->
  <script src="/static/assets/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
  <!-- DataTables -->
  <script src="/static/assets/plugins/datatables/jquery.dataTables.min.js"></script>
  <script src="/static/assets/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
  <script src="/static/assets/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
  <script src="/static/assets/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
  <!-- AdminLTE App -->
  <script src="/static/assets/js/adminlte.min.js"></script>
  <!-- AdminLTE for demo purposes -->
  <script src="/static/assets/js/demo.js"></script>
  <!-- page script -->
  <script>
    $(function () {
      $("#example1").DataTable({
        "responsive": true,
        "autoWidth": false,
      });
      $('#example2').DataTable({
        "paging": true,
        "lengthChange": false,
        "searching": false,
        "ordering": true,
        "info": true,
        "autoWidth": false,
        "responsive": true,
      });
    });
  </script>

{% endblock javascripts %}

core/calls/templates/call_list.html
{% extends "layouts/base.html" %}

{% block title %} Tables Data {% endblock %} 

<!-- Element injected in the BODY element -->
{% block body_class %}  sidebar-mini sidebar-collapse {% endblock body_class %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="/static/assets/plugins/fontawesome-free/css/all.min.css">
  <!-- DataTables -->
  <link rel="stylesheet" href="/static/assets/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
  <link rel="stylesheet" href="/static/assets/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="/static/assets/css/adminlte.min.css">

{% endblock stylesheets %}

{% block content %} 

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Call Center</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Call Center</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            
            <!-- /.card -->

            <div class="card">
              <div class="card-header">
                <h3 class="card-title">Call Center with All Client</h3>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="example1" class="table table-bordered table-striped">
                  <thead>
                  <tr>
                    <th>Rendering engine</th>
                    <th>Browser</th>
                    <th>Platform(s)</th>
                    <th>Engine version</th>
                    <th>CSS grade</th>
                    <th>user</th>
                    <th>action</th>
                  </tr>
                  </thead>
                  <tbody>
                  <tr>
                    {% for person in customers_list %}
                    <td>{{person.PatientName}}</td>
                    <td>{{person.PatientMobile1}}</td>
                    <td>{{person.PatientMobile2}}</td>
                    <td> {{person.BallceBalance}}</td>
                    <td>{{person.RemmainingBalance}}</td>
                    <td>{{person.user}}</td>
                    <td><a class="btn btn-warning" href="{% url 'calls:make_call'  person.id %}">Call</a> </td>
                  </tr>
                  {%endfor%}
                  
                  </tfoot>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
      </div>
      <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

  <!-- jQuery -->
  <script src="/static/assets/plugins/jquery/jquery.min.js"></script>
  <!-- Bootstrap 4 -->
  <script src="/static/assets/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
  <!-- DataTables -->
  <script src="/static/assets/plugins/datatables/jquery.dataTables.min.js"></script>
  <script src="/static/assets/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
  <script src="/static/assets/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
  <script src="/static/assets/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
  <!-- AdminLTE App -->
  <script src="/static/assets/js/adminlte.min.js"></script>
  <!-- AdminLTE for demo purposes -->
  <script src="/static/assets/js/demo.js"></script>
  <!-- page script -->
  <script>
    $(function () {
      $("#example1").DataTable({
        "responsive": true,
        "autoWidth": false,
      });
      $('#example2').DataTable({
        "paging": true,
        "lengthChange": false,
        "searching": false,
        "ordering": true,
        "info": true,
        "autoWidth": false,
        "responsive": true,
      });
    });
  </script>

{% endblock javascripts %}

core/calls/templates/new_call.html
{% extends "layouts/base.html" %}

{% block title %} Bla
nk Page {% endblock %} 

<!-- Element injected in the BODY element -->
{% block body_class %}  sidebar-mini sidebar-collapse {% endblock body_class %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="/static/assets/plugins/fontawesome-free/css/all.min.css">
  <!-- pace-progress -->
  <link rel="stylesheet" href="/static/assets/plugins/pace-progress/themes/black/pace-theme-flat-top.css">
  <!-- adminlte-->
  <link rel="stylesheet" href="/static/assets/css/adminlte.min.css">

{% endblock stylesheets %}

{% block content %}  

  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Register Call Info</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Start</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Call Info</h3>

          <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
              <i class="fas fa-minus"></i>
            </button>
            <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
              <i class="fas fa-times"></i>
            </button>
          </div>
        </div>
        <div class="card-body">
          {% load crispy_forms_tags %}

<form method="post" class="uniForm">
{% csrf_token %}
<div class="row">
  <div class="col-md-6">
    <div class="form-group">
      <label>Statue</label>
      {{ form.Statue |as_crispy_field }}
    </div>
    
  
    <div class="form-group">
      <label>Follow up after:</label>
      {{ form.Followup |as_crispy_field }}
     
    </div>
  </div>
    <!-- /.form-group -->
    <div class="col-md-6">
    <div class="form-group">
      <label>Note:</label>
      {{ form.Note |as_crispy_field }}
    </div>
    <!-- /.form-group -->
  </div>
  <!-- /.col -->
</div>
    <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Save an anther call</button>
                </div>
</form>
        </div>
        <!-- /.card-body -->
        <div class="card-footer">
          Footer
        </div>
        <!-- /.card-footer-->
      </div>
      <!-- /.card -->
      <!-- Default box -->
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Call History</h3>

          <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
              <i class="fas fa-minus"></i>
            </button>
            <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
              <i class="fas fa-times"></i>
            </button>
          </div>
        </div>
        <div class="card-body">
          <table id="example1" class="table table-bordered table-striped">
            <thead>
            <tr>
              <th>Note</th>
              <th>Statue</th>
              <th>Call date</th>
              <th>Follow up days</th>            
              <th>Follow up date</th>
              <th>User</th>
              
            </tr>
            </thead>
            <tbody>
              <tr>
            {% for obj in calls_history %}
            
              <td>{{obj.Note}}</td>
              <td>{{obj.Statue}}</td>
              <td>{{obj.Calldate}}</td>
              <td>{{obj.Followup}}</td>FollowupDate
              <td>{{obj.FollowupDate}}</td>
              <td>{{obj.user}}</td>
            </tr>
            {% endfor %} 
           
            </tfoot>
          </table>
        </div>
        <!-- /.card-body -->
        <div class="card-footer">
          Footer
        </div>
        <!-- /.card-footer-->
      </div>
      <!-- /.card -->

    </section>
    <!-- /.content -->
  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

  <!-- jQuery -->
  <script src="/static/assets/plugins/jquery/jquery.min.js"></script>
  <!-- Bootstrap 4 -->
  <script src="/static/assets/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- pace-progress -->
  <script src="/static/assets/plugins/pace-progress/pace.min.js"></script>
  <!-- AdminLTE App -->
  <script src="/static/assets/js/adminlte.min.js"></script>
  <!-- AdminLTE for demo purposes -->
  <script src="/static/assets/js/demo.js"></script>

{% endblock javascripts %}