core/calls/urls.py
from django.contrib import admin
from django.urls import path, include  # add this
from . import views

app_name = 'calls'
urlpatterns = [

    path('customers_list',views.customers_list,name='call_list'),
    path('follow_up_calls_today',views.Follow_up_calls_today,name='Follow_up_calls'),
    path('follow_up_calls_all',views.Follow_up_calls_all,name='Follow_up_calls_all'),
    path('call/<int:id>/', views.make_call, name='make_call'),


]

core/core/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.contrib import admin
from django.urls import path, include  # add this

urlpatterns = [
    path('admin/', admin.site.urls),          # Django admin route
    #path('admin' , admin.site.urls),          # Django admin route 
    path("", include("authentication.urls")), # Auth routes - login / register
    path("", include("app.urls"))  ,           # UI Kits Html files
    path("", include("testapp.urls")),
    path("", include("novav1.urls")),
    path("", include("event_manage.urls")),
    path("", include("calls.urls")),
    path("select2/", include("django_select2.urls")),
]

core/event_manage/urls.py
from django.contrib import admin
from django.urls import  path
from django.conf.urls import url
from . import views
app_name = 'event_manage'

urlpatterns = [                          
   path('event/', views.event, name="manage-event"),
   url('^calendareve', views.calendar, name='calendar'),
   url('^add_event$', views.add_event, name='add_event'),
   url('^update$', views.update, name='update'),
   url('^remove', views.remove, name='remove'),
    url('^add_event$', views.add_event, name='add_event_to_end'),

    #path('crud/', views.CrudView.as_view(), name='crud_ajax'),
    path('ajax/crud/create/', views.CreateCrudUser.as_view(), name='crud_ajax_create'),
    path('ajax/crud/delete/', views.DeleteCrudUser.as_view(), name='crud_ajax_delete'),
    path('ajax/crud/update/', views.UpdateCrudUser.as_view(), name='crud_ajax_update'),

    path('newevent', views.newevent, name='newevent'), 
    path('event/editevent/<int:event_id>', views.editevent, name='editevent'),

    path('eventreservation/<int:id>', views.update, name='eventreservation'),

    path("eventcreate", views.EventCreateView, name="Event-create"), 
    path("eventcreatenew", views.EventCreateView_new, name="Event-create-new"), 
    path("arrive", views.ArriveCreateView.as_view(), name="Arrive-create"), 
    path("session/<int:id>", views.sessionDetail, name="Session-create"), 
    
    
    path("reception", views.reception_all_reserv, name="reception_all_reserv"), 
    path("reception/arrive", views.reception_reserv_arrive, name="reception_reserv_arrive"), 
    path("reception/srart", views.reception_reserv_srart, name="reception_reserv_srart"), 
    path("balls_entry/<int:event_id>/", views.balls_entry, name="balls_entry"),

    path("onofarrive/<int:id>/", views.onofarrive, name="onofarrive"), 
    path("onofstart/<int:id>/", views.onofarrive, name="onofstart"), 

    
    path('eventtype/<int:id>/', views.make_call_for_events, name='make_call_for_events'),               
    

    path('eventfilter/',views.filter,name="eventfilter"),        

    path('calendertest/',views.calendertest,name="calendertest"), 

     

    path('prametars/<int:id>/',views.dvice_prametars,name="prametars"),
    path("prametarsentry/<int:id>/", views.paramentry, name="prametars_entry"),


    path("prametersreport/<int:id>/", views.prametersreport, name="prametersreport"),

    path("eventparameters/<int:part_id>/<int:id>/", views.allInOneView, name="allInOneView"),

    path('test/<int:id>/',views.test,name="test"), 


]

core/urls.py
from django.contrib import admin
from django.urls import  path

from . import views

urlpatterns = [
    path("newPatient", views.PatientCreateView.as_view(), name="Patient-create"),
    path("newreservation", views.ReservationCreateView.as_view(), name="Reservation-create"),
    path("datareservation", views.ReservationData.as_view(), name="Reservation-data"),
    path("PackagesCreate", views.PackagesCreateView.as_view(), name="Packages-create"),
    path('Patientsearch/',views.Search,name="Patient-search"),
    path("roomCreate", views.RoomCreateView.as_view(), name="room-create"),
    path("area", views.AreaCreateView.as_view(), name="area-create"),
    path("Branch", views.BranchCreateView.as_view(), name="branch-create"), 
    path("Device", views.DeviceCreateView.as_view(), name="Device-create"), 
    path("DoctorIn", views.DoctorInCreateView.as_view(), name="DoctorIn-create"), 
    path("DoctorOut", views.DoctorOutCreateView.as_view(), name="DoctorOut-create"), 
 
    path("adddoctor", views.AddDodtonIN.as_view(), name="add-doctor"),
    path('PackagesCreate/<int:id>/', views.onofPatient, name='onof-Patient'),
    path('area/<int:id>/', views.onofArea, name='onof-Area'),
    path('Branch/<int:id>/', views.onofBranch, name='onof-Branch'),
    path('Device/<int:id>/', views.onofDevice, name='onof-Device'),
    path('DoctorIn/<int:id>/', views.onofDoctorIn, name='onof-DoctorIn'),
    path('DoctorOut/<int:id>/', views.onofDoctorOut, name='onof-DoctorOut'),   
    #path('toggle/', views.toggle),
    path('<int:id>/', views.onofPackages, name='onofPackages'),
    path('Patientdetail/<int:id>/', views.PatientDetailView, name='Patient-detail'),
    path('', views.index, name='index'),
]

core/core/templates/includes/footer.html
  <!-- /.content-wrapper -->
  <footer class="main-footer">
    &copy; <a target="_blank" rel="noopener noreferrer" href="https://adminlte.io">AdminLTE</a>
    - coded by <a target="_blank" rel="noopener noreferrer" href="https://appseed.us">AppSeed</a>
    <div class="float-right d-none d-sm-inline-block">
      <a target="_blank" rel="noopener noreferrer" 
          href="https://appseed.us/admin-dashboards/django-dashboard-adminlte">Django AdminLTE</a> 
    </div>
  </footer>

core/core/templates/includes/layout-collapsed-sidebar.html
{% extends "layouts/base.html" %}

{% block title %} Collapsed Sidebar {% endblock %} 

<!-- Element injected in the BODY element -->
{% block body_class %} sidebar-mini sidebar-collapse {% endblock body_class %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="/static/assets/plugins/fontawesome-free/css/all.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="/static/assets/css/adminlte.min.css">

{% endblock stylesheets %}

{% block content %}  

  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Collapsed Sidebar</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item"><a href="#">Layout</a></li>
              <li class="breadcrumb-item active">Collapsed Sidebar</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <!-- Default box -->
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">Title</h3>

                <div class="card-tools">
                  <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                    <i class="fas fa-minus"></i>
                  </button>
                  <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
                    <i class="fas fa-times"></i>
                  </button>
                </div>
              </div>
              <div class="card-body">
                Start creating your amazing application!
              </div>
              <!-- /.card-body -->
              <div class="card-footer">
                Footer
              </div>
              <!-- /.card-footer-->
            </div>
            <!-- /.card -->
          </div>
        </div>
      </div>
    </section>
    <!-- /.content -->
  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

  <!-- jQuery -->
  <script src="/static/assets/plugins/jquery/jquery.min.js"></script>
  <!-- Bootstrap 4 -->
  <script src="/static/assets/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
  <!-- AdminLTE App -->
  <script src="/static/assets/js/adminlte.min.js"></script>
  <!-- AdminLTE for demo purposes -->
  <script src="/static/assets/js/demo.js"></script>

{% endblock javascripts %}

core/core/templates/includes/navigation.html
{% load notification %}
 <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="index3.html" class="nav-link">Home</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">Contact</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="{% url 'Patient-create' %}" class="nav-link">Add New</a>
      </li>
    </ul>
    
    <!-- SEARCH FORM -->
    <form class="form-inline ml-3"  action="{% url 'search' %}" method="GET" value="{{request.GET.q}}">
    {% csrf_token %}
      <div class="input-group input-group-sm">
        <input class="form-control form-control-navbar" type="text" placeholder="Search" aria-label="Search" name="q" value="{{request.GET.q}}">
        <div class="input-group-append">
          <button class="btn btn-navbar" type="submit" name="submit" value="Search">
            <i class="fas fa-search"></i>
          </button>
        </div>
      </div>
    </form>
    
    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Messages Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-comments"></i>
          <span class="badge badge-danger navbar-badge">{{reserv_today_count}}</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <a href="#" class="dropdown-item">
           
            {%for item in reserv_today %}
            <!-- Message Start -->
            <div class="media">
              <img src="/static/assets/img/user1-128x128.jpg" alt="User Avatar" class="img-size-50 mr-3 img-circle">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  {{item.event_name}}
                  <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">Call me whenever you can...</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            {%endfor%}
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="/static/assets/img/user8-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  John Pierce
                  <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">I got your message bro</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="/static/assets/img/user3-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Nora Silvester
                  <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">The subject goes here</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
        </div>
      </li>
      <!-- Notifications Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-bell"></i>
          <span class="badge badge-warning navbar-badge">15</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <span class="dropdown-item dropdown-header">15 Notifications</span>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-envelope mr-2"></i> 4 new messages
            <span class="float-right text-muted text-sm">3 mins</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-users mr-2"></i> 8 friend requests
            <span class="float-right text-muted text-sm">12 hours</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-file mr-2"></i> 3 new reports
            <span class="float-right text-muted text-sm">2 days</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
          <i class="fas fa-th-large"></i>
        </a>
      </li>
    </ul>
  </nav>
  <!-- /.navbar -->

core/core/templates/includes/scripts.html
<!-- jQuery -->
<script src="/static/assets/plugins/jquery/jquery.min.js"></script>
<!-- jQuery UI 1.11.4 -->
<script src="/static/assets/plugins/jquery-ui/jquery-ui.min.js"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src="/static/assets/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- ChartJS -->
<script src="/static/assets/plugins/chart.js/Chart.min.js"></script>
<!-- Sparkline -->
<script src="/static/assets/plugins/sparklines/sparkline.js"></script>
<!-- JQVMap -->
<script src="/static/assets/plugins/jqvmap/jquery.vmap.min.js"></script>
<script src="/static/assets/plugins/jqvmap/maps/jquery.vmap.usa.js"></script>
<!-- jQuery Knob Chart -->
<script src="/static/assets/plugins/jquery-knob/jquery.knob.min.js"></script>
<!-- daterangepicker -->
<script src="/static/assets/plugins/moment/moment.min.js"></script>
<script src="/static/assets/plugins/daterangepicker/daterangepicker.js"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="/static/assets/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
<!-- Summernote -->
<script src="/static/assets/plugins/summernote/summernote-bs4.min.js"></script>
<!-- overlayScrollbars -->
<script src="/static/assets/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
<!-- AdminLTE App -->
<script src="/static/assets/js/adminlte.js"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="/static/assets/js/pages/dashboard.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="/static/assets/js/demo.js"></script>

core/core/templates/includes/sidebar.html
  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="/" class="brand-link">
      <img src="/static/assets/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
      
      <span class="brand-text font-weight-light">Nova Beauty Centre</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="/static/assets/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="{% url 'logout' %}" class="d-block">
            {{ request.user.username }} - Logout
          </a>
        </div>
      </div>

      <!-- SidebarSearch Form -->
      <div class="form-inline">
        <div class="input-group" data-widget="sidebar-search">
          <input class="form-control form-control-sidebar"  id="mySearch" onkeyup="myFunction()" type="search" placeholder="Search" aria-label="Search">
          <div class="input-group-append">
            <button class="btn btn-sidebar">
              <i class="fas fa-search fa-fw"></i>
            </button>
          </div>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false" id="myMenu">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
               <br> 
               
               <li class="nav-item" >
                <a href="{% url 'search' %}"  class="nav-link">
                  <i class="nav-icon fas fa-search""></i>
                  <p> Historical Search</p>
                </a>
              </li>
              <br>
          <li class="nav-item has-treeview menu-close">
            <a href="#" class="nav-link active">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Dashboard
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'home' %}" class="nav-link active">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Dashboard v1</p>
                </a>
              </li>
              
            </ul>
          </li> 
          <br>
          <!-- <li class="nav-item menu-close">
            <a href="{% url 'search' %}" class="nav-link active">
              <i class="nav-icon fas fa-search"></i>
              <p>
                Search
                <i class="fas fa-angle-left right"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'search' %}" class="nav-link active">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Simple Search</p>
                </a>
              </li>
              
            </ul>
          </li> -->
          
          {% if user.is_staff or user.section_name_id == 1  %}
          <li class="nav-item menu-close">
            <a href="#" class="nav-link active">
              <i class="nav-icon fas fa-bullhorn"></i>
              <p>
                Reception
                <i class="fas fa-angle-left right"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              
              <li class="nav-item">
                <a href="{% url 'event_manage:reception_all_reserv' %}" target="_blank" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Reception</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'event_manage:manage-event' %}" target="_blank" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>calendar</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'Patient-create' %}" target="_blank" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>New</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'just_payment' %}" target="_blank" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Payment</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'balls_transaction' %}" target="_blank" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Pulse Transaction</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'refund' %}" target="_blank" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Refund</p>
                </a>
              </li>
            </ul>
          </li>
          {%endif%}
          <br>
          {% if user.is_staff or user.section_name_id == 2  %}
          <li class="nav-item menu-close">
            <a href="#" class="nav-link active">
              <i class="nav-icon fas fa-phone"></i>
              <p>
                Call Center
                <i class="fas fa-angle-left right"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <!-- <a href="{% url 'search' %}" class="nav-link active">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Simple Search</p>
                </a> -->
              </li>
              <li class="nav-item">
                <a href="{% url 'calls:call_list' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Customers List</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'calls:Follow_up_calls' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Follow up calls today</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'calls:Follow_up_calls_all' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Follow up All calls</p>
                </a>
              </li>
            </ul>
          </li>
          {%endif%}
          <br>
          {% if user.is_staff or user.section_name_id == 4  %}
          
          <li class="nav-item menu-close">
            <a href="#" class="nav-link active">
              <i class="nav-icon fas fa-user-md"></i>
              <p>
                Doctor
                <i class="fas fa-angle-left right"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'event_manage:reception_all_reserv' %}" target="_blank" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Reception</p>
                </a>
              </li>
              
            </ul>
          </li>
          {%endif%}
          <br>
          {% if user.is_staff %}
          <li class="nav-item menu-close">
            <a href="#" class="nav-link active">
              <i class="nav-icon fas fa-cog"></i>
              <p>
                Admin Tools
                <i class="fas fa-angle-left right"></i>
              </p>
            </a>
            <!-- <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'Packages-create' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Laser Packaging</p>
                </a>
              </li> -->
               {% comment %} <li class="nav-item">
                <a href="{% url 'item-create' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>items create</p>
                </a>
              </li> {% endcomment %}
              <li class="nav-item">
                <a href="{% url 'room-create' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Room setting</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'clinic-create' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>clinic setting</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'DoctorOut-create' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>External Doctor</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'DoctorIn-create' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Internal Doctor</p>
                </a>
              </li>  
              <li class="nav-item">
                <a href="{% url 'area-create' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Area setting</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'branch-create' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Branch setting</p>
                </a>
              </li>
             <li class="nav-item">
                <a href="{% url 'Device-create' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Device setting</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'job-create' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Job setting</p>
                </a>
              </li>
              <!-- <li class="nav-item">
                <a href="{% url 'DoctorIn-create' %} " class="nav-link" target="_blank" >
                  <i class="far fa-circle nav-icon"></i>
                  <p>Doctor In setting</p>
                </a>
              </li>    -->
                          
              <li class="nav-item">
                <a href="{% url 'itemP-create' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>leaser</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'itemS-create' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Derma</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'users_list' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Users</p>
                </a>
              </li>
            </ul>
          </li>
          {%endif%}
          <br>
          
          
          
          
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>
  <script>
function myFunction() {
  var input, filter, ul, li, a, i;
  input = document.getElementById("mySearch");
  filter = input.value.toUpperCase();
  ul = document.getElementById("myMenu");
  li = ul.getElementsByTagName("li");
  for (i = 0; i < li.length; i++) {
    a = li[i].getElementsByTagName("a")[0];
    if (a.innerHTML.toUpperCase().indexOf(filter) > -1) {
      li[i].style.display = "";
    } else {
      li[i].style.display = "none";
    }
  }
}
</script>