core/calls/urls.py
from django.contrib import admin
from django.urls import path, include  # add this
from . import views

app_name = 'calls'
urlpatterns = [

    path('customers_list',views.customers_list,name='call_list'),
    path('follow_up_calls_today',views.Follow_up_calls_today,name='Follow_up_calls'),
    path('follow_up_calls_all',views.Follow_up_calls_all,name='Follow_up_calls_all'),
    path('call/<int:id>/', views.make_call, name='make_call'),


]

core/core/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.contrib import admin
from django.urls import path, include  # add this

urlpatterns = [
    path('admin/', admin.site.urls),          # Django admin route
    #path('admin' , admin.site.urls),          # Django admin route 
    path("", include("authentication.urls")), # Auth routes - login / register
    path("", include("app.urls"))  ,           # UI Kits Html files
    path("", include("testapp.urls")),
    path("", include("novav1.urls")),
    path("", include("event_manage.urls")),
    path("", include("calls.urls")),
    path("select2/", include("django_select2.urls")),
]

core/event_manage/urls.py
from django.contrib import admin
from django.urls import  path
from django.conf.urls import url
from . import views
app_name = 'event_manage'

urlpatterns = [                          
   path('event/', views.event, name="manage-event"),
   url('^calendareve', views.calendar, name='calendar'),
   url('^add_event$', views.add_event, name='add_event'),
   url('^update$', views.update, name='update'),
   url('^remove', views.remove, name='remove'),
    url('^add_event$', views.add_event, name='add_event_to_end'),

    #path('crud/', views.CrudView.as_view(), name='crud_ajax'),
    path('ajax/crud/create/', views.CreateCrudUser.as_view(), name='crud_ajax_create'),
    path('ajax/crud/delete/', views.DeleteCrudUser.as_view(), name='crud_ajax_delete'),
    path('ajax/crud/update/', views.UpdateCrudUser.as_view(), name='crud_ajax_update'),

    path('newevent', views.newevent, name='newevent'), 
    path('event/editevent/<int:event_id>', views.editevent, name='editevent'),

    path('eventreservation/<int:id>', views.update, name='eventreservation'),

    path("eventcreate", views.EventCreateView, name="Event-create"), 
    path("eventcreatenew", views.EventCreateView_new, name="Event-create-new"), 
    path("arrive", views.ArriveCreateView.as_view(), name="Arrive-create"), 
    path("session/<int:id>", views.sessionDetail, name="Session-create"), 
    
    
    path("reception", views.reception_all_reserv, name="reception_all_reserv"), 
    path("reception/arrive", views.reception_reserv_arrive, name="reception_reserv_arrive"), 
    path("reception/srart", views.reception_reserv_srart, name="reception_reserv_srart"), 
    path("balls_entry/<int:event_id>/", views.balls_entry, name="balls_entry"),

    path("onofarrive/<int:id>/", views.onofarrive, name="onofarrive"), 
    path("onofstart/<int:id>/", views.onofarrive, name="onofstart"), 

    
    path('eventtype/<int:id>/', views.make_call_for_events, name='make_call_for_events'),               
    

    path('eventfilter/',views.filter,name="eventfilter"),        

    path('calendertest/',views.calendertest,name="calendertest"), 

     

    path('prametars/<int:id>/',views.dvice_prametars,name="prametars"),
    path("prametarsentry/<int:id>/", views.paramentry, name="prametars_entry"),


    path("prametersreport/<int:id>/", views.prametersreport, name="prametersreport"),

    path("eventparameters/<int:part_id>/<int:id>/", views.allInOneView, name="allInOneView"),

    path('test/<int:id>/',views.test,name="test"), 


]

core/urls.py
from django.contrib import admin
from django.urls import  path

from . import views

urlpatterns = [
    path("newPatient", views.PatientCreateView.as_view(), name="Patient-create"),
    path("newreservation", views.ReservationCreateView.as_view(), name="Reservation-create"),
    path("datareservation", views.ReservationData.as_view(), name="Reservation-data"),
    path("PackagesCreate", views.PackagesCreateView.as_view(), name="Packages-create"),
    path('Patientsearch/',views.Search,name="Patient-search"),
    path("roomCreate", views.RoomCreateView.as_view(), name="room-create"),
    path("area", views.AreaCreateView.as_view(), name="area-create"),
    path("Branch", views.BranchCreateView.as_view(), name="branch-create"), 
    path("Device", views.DeviceCreateView.as_view(), name="Device-create"), 
    path("DoctorIn", views.DoctorInCreateView.as_view(), name="DoctorIn-create"), 
    path("DoctorOut", views.DoctorOutCreateView.as_view(), name="DoctorOut-create"), 
 
    path("adddoctor", views.AddDodtonIN.as_view(), name="add-doctor"),
    path('PackagesCreate/<int:id>/', views.onofPatient, name='onof-Patient'),
    path('area/<int:id>/', views.onofArea, name='onof-Area'),
    path('Branch/<int:id>/', views.onofBranch, name='onof-Branch'),
    path('Device/<int:id>/', views.onofDevice, name='onof-Device'),
    path('DoctorIn/<int:id>/', views.onofDoctorIn, name='onof-DoctorIn'),
    path('DoctorOut/<int:id>/', views.onofDoctorOut, name='onof-DoctorOut'),   
    #path('toggle/', views.toggle),
    path('<int:id>/', views.onofPackages, name='onofPackages'),
    path('Patientdetail/<int:id>/', views.PatientDetailView, name='Patient-detail'),
    path('', views.index, name='index'),
]

core/event_manage/views.py
from django.shortcuts import render ,redirect ,get_object_or_404 
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.views import generic
from .models import Events , CrudUser ,EventType ,deviceparameters ,Event
from novav1.models import Patient ,DoctorIn , pricing ,Patient ,Branch,DoctorIn,pricing,Clinc,Category
from .forms  import EventForm ,ArriveForm , SessionDetail ,callsFormsEvents,ParametersForms
from django.views.generic import TemplateView, View, DeleteView
from django.http import HttpResponseRedirect
from django.http import JsonResponse
from datetime import datetime ,date ,timedelta
from .filter import EventsFilter
from django.db.models import Q 
from django.db.models import Max ,F
from itertools import zip_longest 
from .utils import  twilio_send_sms ,twilio_send_whatsapp
from django.db import models
from django.db.models import When, F, Q

#Create your views here.

# def event(request):
#     all_events = Events.objects.all()
#     get_event_types = Events.objects.only('event_type')

#     # if filters applied then get parameter and filter based on condition else return object
#     # if request.GET:  
#     #     event_arr = []
#     #     if request.GET.get('event_type') == "all":#
#     #         all_events = Events.objects.all()
#     #     else:   
#     #         all_events = Events.objects.filter(event_type__icontains=request.GET.get('event_type'))
            
#     #     for i in all_events:
#     #         event_sub_arr = {}
#     #         event_sub_arr['title'] = i.event_name
#     #         start_date = datetime.datetime.strptime(str(i.start_date.date()), "%Y-%m-%d").strftime("%Y-%m-%d")
#     #         end_date = datetime.datetime.strptime(str(i.end_date.date()), "%Y-%m-%d").strftime("%Y-%m-%d")
#     #         event_sub_arr['start'] = start_date
#     #         event_sub_arr['end'] = end_date
#     #         event_arr.append(event_sub_arr)
#     #     return HttpResponse(json.dumps(event_arr))

#     context = {
#         "events":all_events,
#         #"get_event_types":get_event_types,

#     }
#     return render(request,'core/templates/calendar.html',context)


def event(request):
    pe  = Patient.objects.all()
    ev   = Events.objects.all()
    Cl   = Clinc.objects.all()
    Doc   = DoctorIn.objects.all()
    Br  = Branch.objects.all()
    pr   = pricing.objects.all()
    cat   = Category.objects.all()
    today = datetime.now().date()
    tomorrow = today + timedelta(1)
    filter = EventsFilter(request.GET, queryset=Events.objects.all())
    
    context = {
        'pe':pe,
        'Cl':Cl,
        'Doc':Doc,
        'Br':Br,
        'pr':pr,
        'cat':cat,
        'filter':filter,


    }
    return render(request,'core/templates/calendar_last.html',context)  #calendar_last.html



def calendar(request):
    all_events = Events.objects.all()
    context = {
        "events":all_events,
    }
    return render(request,'core/templates/calendar2.html',context)

def add_event(request):
    start = request.GET.get("start", None)
    end = request.GET.get("end", None)
    title = request.GET.get("title", None)
    event = Events(name=str(title), start=start, end=end)
    event.save()
    data = {}
    return JsonResponse(data)


def update(request):
    start = request.GET.get("start", None)
    end = request.GET.get("end", None)
    title = request.GET.get("title", None)
    id = request.GET.get("id", None)
    event = Events.objects.get(id=id)
    event.start = start
    event.end = end
    event.name = title
    event.save()
    data = {}
    return JsonResponse(data)


def remove(request):
    id = request.GET.get("id", None)
    event = Events.objects.get(id=id)
    event.delete()
    data = {}
    return JsonResponse(data)





class CreateCrudUser(View):
    def  get(self, request):
        name1 = request.GET.get('name', None)
        address1 = request.GET.get('address', None)
        age1 = request.GET.get('age', None)

        obj = CrudUser.objects.create(
            name = name1,
            address = address1,
            age = age1
        )

        user = {'id':obj.id,'name':obj.name,'address':obj.address,'age':obj.age}

        data = {
            'user': user
        }
        return JsonResponse(data)

class DeleteCrudUser(View):
    def  get(self, request):
        id1 = request.GET.get('id', None)
        CrudUser.objects.get(id=id1).delete()
        data = {
            'deleted': True
        }
        return JsonResponse(data)


class UpdateCrudUser(View):
    def  get(self, request):
        id1 = request.GET.get('id', None)
        name1 = request.GET.get('name', None)
        address1 = request.GET.get('address', None)
        age1 = request.GET.get('age', None)

        obj = CrudUser.objects.get(id=id1)
        obj.name = name1
        obj.address = address1
        obj.age = age1
        obj.save()

        user = {'id':obj.id,'name':obj.name,'address':obj.address,'age':obj.age}

        data = {
            'user': user
        }
        return JsonResponse(data)    




def add_event_to_end(request):
    start = request.GET.get("start", None)
    end = request.GET.get("end", None)
    title = request.GET.get("title", None)
    Events = Events(name=str(event_name), start=start_date, end=end_date)
    Events.save()
    data = {}
    return JsonResponse(data)        


# class newevent(View):
#     def  get(self, request):
def newevent(request):
    #if request.method=='POST':
        Patients  = Patient.objects.get(pk=int(request.POST['Patient']))
        to= Patients.PatientMobile1
        pname= Patients.PatientName
        doctors= DoctorIn.objects.get(pk=request.POST.get('doctor'))
        eventdoctor=doctors.DocName

        event_name     = Patient.objects.get(pk=request.POST.get('Patient'))
        start_date     = request.POST['evtEnd']
        #end_date       = request.POST['end_date']
        event_clinic = Clinc.objects.get(pk=request.POST.get('clinic'))
        event_doctor   = DoctorIn.objects.get(pk=request.POST.get('doctor'))
        branch_event   = Branch.objects.get(pk=request.POST.get('branch'))
        area_list      = request.POST.getlist('area')
        event_area     = pricing.objects.filter(pk__in=area_list)
        category       = Category.objects.get(pk=request.POST.get('cat'))
        user           = request.user
        areas = pricing.objects.filter(pk__in=area_list)
        #servic_kind    = request.POST['cat']

       
        
        
        
        obj = Events.objects.create(
            event_name = event_name,
            start_date = start_date,
            #end_date = end_date,
            event_clinic=event_clinic,
            event_doctor=event_doctor,
            branch_event=branch_event,
            event_service=category
            
        )
       
        for ar in areas:
            obj.event_area.add(ar)


        if obj.event_service_id == 1 :
            time=0
            for pt in areas:
                time += pt.time_of_part

                sd = datetime_object = datetime.strptime(start_date, "%Y-%m-%d %H:%M:%S")
                minutes = time
                ed = timedelta(minutes = minutes)
                end_dateu = sd+ed
                obj.end_date=end_dateu
                obj.save()
        else:
                sd = datetime_object = datetime.strptime(start_date, "%Y-%m-%d %H:%M:%S")
                ed = timedelta(minutes = 30)
                obj.end_date= sd+ed
                obj.save()


       
        body= f'مساء الخير استاذه {pname} معاكي مركز نوفا بناكد ع حضرتك معاد جلستنا بكره الساعه  {start_date} مع دكتوره {eventdoctor} و منطقة { event_area}وفتره الانتظار من نص ساعه لساعه'
        
        #twilio_send_sms(body,to)
        #twilio_send_whatsapp(body,to)

        print(request)
        return redirect ('/event')
    #return redirect ('/')

def editevent(request,event_id):
    obj = Events.objects.get(event_id=event_id)
    pe  = Patient.objects.all()
    ev   = Events.objects.all()
    Cl   = Clinc.objects.all()
    Doc   = DoctorIn.objects.all()
    Br  = Branch.objects.all()
    pr   = pricing.objects.all()
    cat   = Category.objects.all()

    if request.method=='POST':
        Patients  = Patient.objects.get(pk=int(request.POST['Patient']))
        to= Patients.PatientMobile1
        pname= Patients.PatientName
        doctors= DoctorIn.objects.get(pk=request.POST.get('doctor', None))
        eventdoctor=doctors.DocName

        
        event_name     = Patient.objects.get(pk=request.POST.get('Patient', None))
        #start_date     = request.POST['evtEnd']
        #end_date       = request.POST['end_date']
        event_clinic = Clinc.objects.get(pk=request.POST.get('clinic', None))
        event_doctor   = DoctorIn.objects.get(pk=request.POST.get('doctor', None))
        branch_event   = Branch.objects.get(pk=request.POST.get('branch', None))
        area_list      = request.POST.getlist('area', None)
        event_area     = pricing.objects.filter(pk__in=area_list)
        category       = Category.objects.get(pk=request.POST.get('cat', None))
        user           = request.user
        areas = pricing.objects.filter(pk__in=area_list)
        #servic_kind    = request.POST['cat']

       
        
        obj = Events.objects.get(event_id=event_id)
        obj.event_name = event_name
       
        obj.event_clinic = event_clinic
        obj.event_doctor = event_doctor
        obj.branch_event = branch_event
        obj.event_service = category
        obj.save()

        

        
        # obj = Events.objects.create(
        #     event_name = event_name,
        #     start_date = start_date,
        #     #end_date = end_date,
        #     event_clinic=event_clinic,
        #     event_doctor=event_doctor,
        #     branch_event=branch_event,
        #     event_service=category
            
        # )
       

core/event_manage/templates/date-picker.html
<h5>This is a customized date-picker</h5>
<div class="input-group date my-custom-class">
    {% include "bootstrap_datepicker_plus/input.html" %}
    <div class="input-group-addon input-group-append">
        <div class="input-group-text"><i class="glyphicon glyphicon-calendar"></i></div>
    </div>
</div>

core/event_manage/templates/editor.html
{% extends "layouts/base.html" %}
{% load crispy_forms_tags %}
{% block title %} Regestrations Form{% endblock %} 

<!-- Element injected in the BODY element -->
{% block body_class %} sidebar-mini sidebar-collapse {% endblock body_class %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="/static/assets/plugins/fontawesome-free/css/all.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="/static/assets/css/adminlte.min.css">
    
{% endblock stylesheets %}

{% block content %}    

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Regestrations Form</h1>  {{Patients.PatientName}}
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="/">Home</a></li>
              <li class="breadcrumb-item active">Regestrations Form</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <!-- left column -->
          <div class="col-md-6">
            <!-- general form elements -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">{{parametername.BodyPart}}</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              
                <div class="card-body">
                  
                  <form method="POST">
                    {% csrf_token %}
                    {{form|crispy}}
                  
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              
            </div>
            <!-- /.card -->

            <!-- Form Element sizes -->
            <div class="card card-success">
              <div class="card-header">
                <h3 class="card-title">Different Height</h3>
              </div>
              
              <!-- /.card-body -->
            </div> </div>
            <!-- /.card -->
            <!-- /.card -->
            <!-- Default box -->
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Doctor in Data</h3>

          <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
              <i class="fas fa-minus"></i>
            </button>
            <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
              <i class="fas fa-times"></i>
            </button>
          </div>
        </div>
        <div class="card-body">
          <div class="row"></div>
         <table id="example1" class="table table-bordered table-striped">
                  <thead>
                  <tr>
                    <th>Doctor In Name</th>
                    <th>statu</th>
                    
                    
                  </tr>
                  </thead>
                  <tbody>
                  {% for obj in parts %}
                  <tr>
                    <td>{{obj.BodyPart}}</td>
                    <td><a class="btn btn-warning" href="{% url 'event_manage:allInOneView'  obj.id  Patients.id  %}">Change</a> </td>
                  </tr>
                  {% endfor %} 
                 
                  </tfoot>
                </table>
               
                </div></div>
        <!-- /.card-body -->
{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

  <!-- jQuery -->
  <script src="/static/assets/plugins/jquery/jquery.min.js"></script>
  <!-- Bootstrap 4 -->
  <script src="/static/assets/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
  <!-- bs-custom-file-input -->
  <script src="/static/assets/plugins/bs-custom-file-input/bs-custom-file-input.min.js"></script>
  <!-- AdminLTE App -->
  <script src="/static/assets/js/adminlte.min.js"></script>
  <!-- AdminLTE for demo purposes -->
  <script src="/static/assets/js/demo.js"></script>
  <script>
  $(function () {
    bsCustomFileInput.init();
  });
  </script>



  

{% endblock javascripts %}

core/event_manage/templates/receipt.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="stylesheet" href="style.css">
		<title>Receipt example</title>
		<style>
* {
font-size: 12px;
font-family: 'Times New Roman';
}

td,
th,
tr,
table {
    border-top: 1px solid black;
    border-collapse: collapse;
}

td.description,
th.description {
    width: 75px;
    max-width: 75px;
}

td.quantity,
th.quantity {
    width: 40px;
    max-width: 40px;
    word-break: break-all;
}

td.price,
th.price {
    width: 40px;
    max-width: 40px;
    word-break: break-all;
}

.centered {
    text-align: center;
    align-content: center;
}

.ticket {
    width: 155px;
    max-width: 155px;
}

img {
    max-width: inherit;
    width: inherit;
}

@media print {
    .hidden-print,
    .hidden-print * {
        display: none !important;
    }
}	
		</style>
    </head>
    <body>
        <div class="ticket">
            <!-- <img src="./logo.png" alt="Logo"> -->
            <h4>Nova<h4>
            <p class="centered">Device parameters </p> 
        
            <table>
                <thead>
                    <tr>
                        
                        <th>Area Name</th>              
                <th>Date</th>
                <th>Joule</th>
                <th>msec</th>              
                
                
                    </tr>
                </thead>
                <tbody>
                    {% for obj in eventsprametars %}
                    <tr>
                        
                        <td>{{obj.part}}</td>
                        <td>{{obj.Date|date:'Y-m-d'}}</td>
                        <td>{{obj.Joule}}</td>
                        <td>{{obj.msec}}</td>
                        	
                    </tr>
                    {%endfor%}
                </tbody>
            </table>
            <p class="centered">Thanks for your visit!
                <br>We wish you a good time</p>
        </div>
        <button id="btnPrint" class="hidden-print">Print</button>
        <script>
		const $btnPrint = document.querySelector("#btnPrint");
		$btnPrint.addEventListener("click", () => {
			window.print();
		});	
		</script>
    </body>
</html>

core/event_manage/templates/reseptions_arrive.html
{% extends "layouts/base.html" %}

{% block title %} Tables Data {% endblock %} 

<!-- Element injected in the BODY element -->
{% block body_class %} sidebar-mini sidebar-collapse {% endblock body_class %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="/static/assets/plugins/fontawesome-free/css/all.min.css">
  <!-- DataTables -->
  <link rel="stylesheet" href="/static/assets/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
  <link rel="stylesheet" href="/static/assets/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="/static/assets/css/adminlte.min.css">

{% endblock stylesheets %}

{% block content %} 

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>DataTables</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">DataTables</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
      <a href="{% url 'event_manage:reception_all_reserv'  %}" class="btn btn-outline-primary">All</a>
      <a href="{% url 'event_manage:reception_reserv_arrive'  %}" class="btn btn-outline-secondary">Arrive</a>
      <a href="{% url 'event_manage:reception_reserv_srart'  %}" class="btn btn-outline-primary">Start</a>
      <!-- <a href="" class="btn btn-outline-secondary">تم التسليم للعميل</a> -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            
            <!-- /.card -->

            <div class="card">
              <div class="card-header">
                <h3 class="card-title">Customer Arrive list</h3>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="example1" class="table table-bordered table-striped">
                  <thead>
                  <tr>
                    <th> Name</th>
                    <th>From</th>
                    <th>To</th>             
                    <th>statu</th>
                    <th>Change statu</th>
                    <th>parametars</th>
                  </tr>
                  </thead>
                  <tbody>
                  {% for obj in reserv_arrive %}
                  <tr>
                    <td>{{obj.event_name}}</td>
                    <td>{{obj.start_date}}</td>
                    <td>{{obj.end_date}}</td>
                      {% if obj.arrive == True %}
                            <td class="p-3 mb-2 bg-success text-white" >Active </span></td>

                            {% else %}
                            <td class="p-3 mb-2 bg-danger text-white">Inactive </td>
                            {% endif %}
                            <td><a class="btn btn-warning" href="{% url 'event_manage:Session-create'  obj.event_id %}">Start</a> </td>
                            <td><a class="btn btn-warning" href="{% url 'event_manage:allInOneView' part_id=1  id=obj.event_name_id  %}" target="_blank">parametars</a> </td>
                        </tr>
                   
                       
                  {% endfor %} 
                 
                  </tfoot>
                </table>
        </div>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
      </div>
      <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

  <!-- jQuery -->
  <script src="/static/assets/plugins/jquery/jquery.min.js"></script>
  <!-- Bootstrap 4 -->
  <script src="/static/assets/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
  <!-- DataTables -->
  <script src="/static/assets/plugins/datatables/jquery.dataTables.min.js"></script>
  <script src="/static/assets/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
  <script src="/static/assets/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
  <script src="/static/assets/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
  <!-- AdminLTE App -->
  <script src="/static/assets/js/adminlte.min.js"></script>
  <!-- AdminLTE for demo purposes -->
  <script src="/static/assets/js/demo.js"></script>
  <!-- page script -->
  <script>
    $(function () {
      $("#example1").DataTable({
        "responsive": true,
        "autoWidth": false,
      });
      $('#example2').DataTable({
        "paging": true,
        "lengthChange": false,
        "searching": false,
        "ordering": true,
        "info": true,
        "autoWidth": false,
        "responsive": true,
      });
    });
  </script>

{% endblock javascripts %}